version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /my-app/docker-creds/username
    DOCKER_REGISTRY_PASSWORD: /my-app/docker-creds/passwd
    DOCKER_REGISTRY_URL: /my-app/docker-creds/docker_registry/url

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "Building React Docker image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest" .

  post_build:
    commands:
      - echo "Pushing React Docker image to Docker Hub"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/react-app:latest"
      - echo "Build and push successful"
